Improve network optimization and related systems
safing/spn pull request #49
Opened 2022-01-24 15:50 UTC by dhaavi

- Increase timeouts related to verifying Hubs
- Improve pin update order
- Add support for discontinued Hubs, fix Hub deletion
- Make measurement TTL dynamic to save bandwidth
- Reduce default capacity test volume to 25MB
- Remove unnecessary check
- Sync crane status to connected Hub
- Update QueueSize to uint32 and increase controller queue size
- Disable kcp until we find a replacement
- Don't die when the intel update fails on startup
- Add time limit to stopping cranes
- Increase capacity test volume to 50MB again
- Raise hub costs to better match lane costs
- Add regions for optimization

2022-01-25 08:02 UTC, ppacher requested changes

2022-01-25 08:26 UTC, dhaavi commented on docks/crane.go
>  )
Yes, there may be long-running connections we don't want to break routinely.

2022-01-25 08:27 UTC, dhaavi commented on docks/crane.go
> +
The stopping flag is authoritative, the timestamp is only a helper for the stopping timeout.

2022-01-25 08:27 UTC, dhaavi commented on navigator/region.go
> +	"github.com/apex/log"
Aaaah! Thanks!

2022-01-26 13:12 UTC, ppacher approved these changes

2022-01-26 13:16 UTC, merged